#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/app/api/projects/[id]/generate/route.ts');
let content = fs.readFileSync(filePath, 'utf-8');

const replacements = [
  ['console.log(`[Generate API] action=${action}, episodeId=${episodeId}`);', 'logger.info(`action=${action}, episodeId=${episodeId}`);'],
  ['console.log(`[ScriptOutline] Saved outline for ${episodeId || projectId}`);', 'logger.info(`Saved outline for ${episodeId || projectId}`);'],
  ['console.error("[ScriptOutline] onFinish error:", err);', 'logger.error("onFinish error", err);'],
  ['console.log(`[ScriptGenerate] Saved generated script for ${episodeId || projectId}`);', 'logger.info(`Saved generated script for ${episodeId || projectId}`);'],
  ['console.error("[ScriptGenerate] onFinish error:", err);', 'logger.error("onFinish error", err);'],
  ['console.log(`[ScriptParse] Parsed screenplay for ${episodeId || projectId}`);', 'logger.info(`Parsed screenplay for ${episodeId || projectId}`);'],
  ['console.error("[ScriptParse] onFinish error:", err);', 'logger.error("onFinish error", err);'],
  ['console.log("[CharacterExtract] resolved system prompt:\\n", charExtractSystem);', 'logger.debug("resolved system prompt", charExtractSystem);'],
  ['console.log("[CharacterExtract] Raw AI response:\\n", text);', 'logger.debug("Raw AI response", text);'],
  ['console.log("[CharacterExtract] Response length:", text.length);', 'logger.debug(`Response length: ${text.length}`);'],
  ['console.log("[CharacterExtract] Extracted JSON:\\n", extractedJSON);', 'logger.debug("Extracted JSON", extractedJSON);'],
  ['console.error("[CharacterExtract] JSON parse error:", error);', 'logger.error("JSON parse error", error);'],
  ['console.error("[CharacterExtract] Failed to parse text:", text.substring(0, 1000));', 'logger.error("Failed to parse text", text.substring(0, 1000));'],
  ['console.log("[CharacterExtract] Fallback: extracted character names:", nameMatches);', 'logger.info("Fallback: extracted character names", nameMatches);'],
  ['console.log("[CharacterExtract] Fallback: valid characters extracted:", extracted.length);', 'logger.info(`Fallback: valid characters extracted: ${extracted.length}`);'],
  ['console.warn("[CharacterExtract] No valid characters extracted, skipping character processing");', 'logger.warn("No valid characters extracted, skipping character processing");'],
  ['console.log(`[CharacterExtract] Updated existing character "${char.name}" (${existing.id}), desc length: ${char.description.length}`);', 'logger.info(`Updated existing character "${char.name}" (${existing.id}), desc length: ${char.description.length}`);'],
  ['console.error(`[SingleCharacterImage] Error for ${character.name}:`, err);', 'logger.error(`Error for ${character.name}`, err);'],
  ['console.log(`[BatchCharacterImage] Using sequential execution for ComfyUI (${needImages.length} items)`);', 'logger.info(`Using sequential execution for ComfyUI (${needImages.length} items)`);'],
  ['console.log(`[BatchCharacterImage] ✓ ${character.name} (${i + 1}/${needImages.length})`);', 'logger.info(`✓ ${character.name} (${i + 1}/${needImages.length})`);'],
  ['console.error(`[BatchCharacterImage] Error for ${character.name}:`, err);', 'logger.error(`Error for ${character.name}`, err);'],
  ['console.log(`[ShotSplit] Starting: projectId=${projectId}, episodeId=${episodeId}`);', 'logger.info(`Starting: projectId=${projectId}, episodeId=${episodeId}`);'],
  ['console.log(`[ShotSplit] Detected ${sceneMatches.length} scenes, split into ${sceneChunks.length} chunk(s) of ~8 scenes each`);', 'logger.info(`Detected ${sceneMatches.length} scenes, split into ${sceneChunks.length} chunk(s) of ~8 scenes each`);'],
  ['console.log(`[ShotSplit] Chunk ${i + 1}: ${sceneCount} scenes, ${c.length} chars`);', 'logger.debug(`Chunk ${i + 1}: ${sceneCount} scenes, ${c.length} chars`);'],
  ['console.log(`[ShotSplit] Chunk ${idx + 1}/${sceneChunks.length}: ${shotList.length} shots, keys: ${shotList[0] ? Object.keys(shotList[0]).join(",") : "empty"}`);', 'logger.debug(`Chunk ${idx + 1}/${sceneChunks.length}: ${shotList.length} shots, keys: ${shotList[0] ? Object.keys(shotList[0]).join(",") : "empty"}`);'],
  ['console.error(`[ShotSplit] Chunk ${idx + 1} failed:`, err);', 'logger.error(`Chunk ${idx + 1} failed`, err);'],
  ['console.log(`[ShotSplit] Created version: id=${versionId}, episodeId=${episodeId ?? null}`);', 'logger.info(`Created version: id=${versionId}, episodeId=${episodeId ?? null}`);'],
  ['console.log(`[ShotSplit] Creating shot: sequence=${shot.sequence}, episodeId=${episodeId ?? null}`);', 'logger.debug(`Creating shot: sequence=${shot.sequence}, episodeId=${episodeId ?? null}`);'],
  ['console.log(`[ShotSplit] Shot inserted: id=${shotId}, episodeId=${episodeId ?? null}`);', 'logger.debug(`Shot inserted: id=${shotId}, episodeId=${episodeId ?? null}`);'],
  ['console.log(`[ShotSplit] Created ${allShots.length} shots from ${sceneChunks.length} chunks`);', 'logger.info(`Created ${allShots.length} shots from ${sceneChunks.length} chunks`);'],
  ['console.log(`[SingleShotRewrite] Shot ${shot.sequence} prompt:\\n${prompt}`);', 'logger.debug(`Shot ${shot.sequence} prompt`, prompt);'],
  ['console.error(`[SingleShotRewrite] Error for shot ${shotId}:`, err);', 'logger.error(`Error for shot ${shotId}`, err);'],
  ['console.log(`[BatchFrameGenerate] Starting sequential generation with SSE: 0/${total}`);', 'logger.info(`Starting sequential generation with SSE: 0/${total}`);'],
  ['console.log(`[BatchFrameGenerate] ⊙ shot ${shot.sequence} skipped (${doneCount}/${total})`);', 'logger.debug(`⊙ shot ${shot.sequence} skipped (${doneCount}/${total})`);'],
  ['console.log(`[BatchFrameGenerate] ✓ shot ${shot.sequence} (${doneCount}/${total}) ${elapsed}s`);', 'logger.info(`✓ shot ${shot.sequence} (${doneCount}/${total}) ${elapsed}s`);'],
  ['console.error(`[BatchFrameGenerate] ✗ shot ${shot.sequence} (${doneCount}/${total}) ${elapsed}s:`, err);', 'logger.error(`✗ shot ${shot.sequence} (${doneCount}/${total}) ${elapsed}s`, err);'],
  ['console.log(`[BatchFrameGenerate] Done: ${okCount} ok, ${errCount} errors`);', 'logger.info(`Done: ${okCount} ok, ${errCount} errors`);'],
  ['console.error("[BatchFrameGenerate] Stream error:", err);', 'logger.error("Stream error", err);'],
  ['console.error(`[SingleFrameGenerate] Error for shot ${shotId}:`, err);', 'logger.error(`Error for shot ${shotId}`, err);'],
  ['console.error(`[SingleVideoGenerate] Error for shot ${shotId}:`, err);', 'logger.error(`Error for shot ${shotId}`, err);'],
  ['console.log(`[BatchVideoGenerate] Processing ${eligible.length} shots`);', 'logger.info(`Processing ${eligible.length} shots`);'],
  ['console.log(`[BatchVideoGenerate] Execution mode: ${useSequential ? "SEQUENTIAL (ComfyUI)" : "PARALLEL"}`);', 'logger.info(`Execution mode: ${useSequential ? "SEQUENTIAL (ComfyUI)" : "PARALLEL"}`);'],
  ['console.log(`[BatchVideoGenerate] ✓ shot ${shot.sequence} (${i + 1}/${eligible.length})`);', 'logger.info(`✓ shot ${shot.sequence} (${i + 1}/${eligible.length})`);'],
  ['console.error(`[BatchVideoGenerate] ✗ shot ${shot.sequence} (${i + 1}/${eligible.length}):`, err);', 'logger.error(`✗ shot ${shot.sequence} (${i + 1}/${eligible.length})`, err);'],
  ['console.log(`[BatchVideoGenerate] Shot ${shot.sequence} completed`);', 'logger.debug(`Shot ${shot.sequence} completed`);'],
  ['console.error(`[BatchVideoGenerate] Error for shot ${shot.sequence}:`, err);', 'logger.error(`Error for shot ${shot.sequence}`, err);'],
  ['console.log(`[SingleSceneFrame] Shot ${shot.sequence}: generating scene-only frame (no character refs)`);', 'logger.debug(`Shot ${shot.sequence}: generating scene-only frame (no character refs)`);'],
  ['console.error(`[SingleSceneFrame] Error for shot ${shot.sequence}:`, err);', 'logger.error(`Error for shot ${shot.sequence}`, err);'],
  ['console.log(`[BatchSceneFrame] Processing ${allShots.length} shots, ${eligible.length} eligible`);', 'logger.info(`Processing ${allShots.length} shots, ${eligible.length} eligible`);'],
  ['console.log(`[BatchSceneFrame] Execution mode: ${useSequential ? "SEQUENTIAL (ComfyUI)" : "PARALLEL"}`);', 'logger.info(`Execution mode: ${useSequential ? "SEQUENTIAL (ComfyUI)" : "PARALLEL"}`);'],
  ['console.log(`[BatchSceneFrame] Shot ${shot.sequence} (${i + 1}/${allShots.length}): ${targets.length} refs`);', 'logger.debug(`Shot ${shot.sequence} (${i + 1}/${allShots.length}): ${targets.length} refs`);'],
  ['console.log(`[BatchRefImage] Shot ${shot.sequence}: ref "${entry.id}" done`);', 'logger.debug(`Shot ${shot.sequence}: ref "${entry.id}" done`);'],
  ['console.warn(`[BatchRefImage] Shot ${shot.sequence} ref ${entry.id} failed:`, err);', 'logger.warn(`Shot ${shot.sequence} ref ${entry.id} failed`, err);'],
  ['console.log(`[BatchSceneFrame] Shot ${shot.sequence}: ${targets.length} scene-only refs (no character injection)`);', 'logger.debug(`Shot ${shot.sequence}: ${targets.length} scene-only refs (no character injection)`);'],
  ['console.log(`[SingleReferenceVideo] Shot ${shot.sequence}: ${sceneFramePaths.length} scene frame(s), ${charRefs.length} character ref(s)`);', 'logger.debug(`Shot ${shot.sequence}: ${sceneFramePaths.length} scene frame(s), ${charRefs.length} character ref(s)`);'],
  ['console.log(`[SingleReferenceVideo] Shot ${shot.sequence} promptRequest:\\n${promptRequest}`);', 'logger.debug(`Shot ${shot.sequence} promptRequest`, promptRequest);'],
  ['console.warn("[SingleReferenceVideo] Vision prompt generation failed, falling back:", err);', 'logger.warn("Vision prompt generation failed, falling back", err);'],
  ['console.log(`[SingleReferenceVideo] Shot ${shot.sequence}: generating video with ${orderedRefImages.length} reference images`);', 'logger.debug(`Shot ${shot.sequence}: generating video with ${orderedRefImages.length} reference images`);'],
  ['console.error(`[SingleReferenceVideo] Error for shot ${shot.sequence}:`, err);', 'logger.error(`Error for shot ${shot.sequence}`, err);'],
  ['console.log(`[BatchReferenceVideo] Processing ${eligible.length} shots`);', 'logger.info(`Processing ${eligible.length} shots`);'],
  ['console.log(`[BatchReferenceVideo] Execution mode: ${useSequential ? "SEQUENTIAL (ComfyUI)" : "PARALLEL"}`);', 'logger.info(`Execution mode: ${useSequential ? "SEQUENTIAL (ComfyUI)" : "PARALLEL"}`);'],
  ['console.warn("[BatchReferenceVideo] Vision prompt generation failed, falling back:", err);', 'logger.warn("Vision prompt generation failed, falling back", err);'],
  ['console.log(`[BatchReferenceVideo] Shot ${shot.sequence} (${i + 1}/${eligible.length}): ${sceneFramePaths.length} scenes + ${charRefs.length} chars → video`);', 'logger.info(`Shot ${shot.sequence} (${i + 1}/${eligible.length}): ${sceneFramePaths.length} scenes + ${charRefs.length} chars → video`);'],
  ['console.log(`[BatchReferenceVideo] ✓ shot ${shot.sequence} (${i + 1}/${eligible.length})`);', 'logger.info(`✓ shot ${shot.sequence} (${i + 1}/${eligible.length})`);'],
  ['console.error(`[BatchReferenceVideo] ✗ shot ${shot.sequence} (${i + 1}/${eligible.length}):`, err);', 'logger.error(`✗ shot ${shot.sequence} (${i + 1}/${eligible.length})`, err);'],
  ['console.log(`[BatchReferenceVideo] Shot ${shot.sequence}: ${sceneFramePaths.length} scenes + ${charRefs.length} chars → video`);', 'logger.debug(`Shot ${shot.sequence}: ${sceneFramePaths.length} scenes + ${charRefs.length} chars → video`);'],
  ['console.log(`[BatchReferenceVideo] Shot ${shot.sequence} completed`);', 'logger.debug(`Shot ${shot.sequence} completed`);'],
  ['console.error(`[BatchReferenceVideo] Error for shot ${shot.sequence}:`, err);', 'logger.error(`Error for shot ${shot.sequence}`, err);'],
  ['console.log(`[VideoAssemble] Completed: ${result.videoPath}`);', 'logger.info(`Completed: ${result.videoPath}`);'],
  ['console.error("[VideoAssemble] Error:", err);', 'logger.error("Error", err);'],
  ['console.log(`[SingleVideoPrompt] called, shotId=${shotId}`);', 'logger.debug(`called, shotId=${shotId}`);'],
  ['console.log(`[SingleVideoPrompt] shot.sequence=${shot.sequence}, mode=${genMode}, frames=${visionFrames.length}`);', 'logger.debug(`shot.sequence=${shot.sequence}, mode=${genMode}, frames=${visionFrames.length}`);'],
  ['console.log(`[SingleVideoPrompt] Shot ${shot.sequence} promptRequest:\\n${promptRequest}`);', 'logger.debug(`Shot ${shot.sequence} promptRequest`, promptRequest);'],
  ['console.log(`[SingleVideoPrompt] Shot ${shot.sequence} videoPrompt:\\n${videoPrompt}`);', 'logger.debug(`Shot ${shot.sequence} videoPrompt`, videoPrompt);'],
  ['console.error("[SingleVideoPrompt] Error:", err);', 'logger.error("Error", err);'],
  ['console.log(`[BatchVideoPrompt] Processing ${eligible.length} shots (${batchShots.length} total, ${batchCharacters.length} chars, mode=${batchGenMode}, concurrency=${VIDEO_PROMPT_CONCURRENCY})`);', 'logger.info(`Processing ${eligible.length} shots (${batchShots.length} total, ${batchCharacters.length} chars, mode=${batchGenMode}, concurrency=${VIDEO_PROMPT_CONCURRENCY})`);'],
  ['console.log(`[BatchVideoPrompt] Shot ${shot.sequence} visionFrames:`, visionFrames.map((f) => ({ path: f, exists: path.resolve(f).startsWith("/") && fs.existsSync(path.resolve(f)) })));', 'logger.debug(`Shot ${shot.sequence} visionFrames`, visionFrames.map((f) => ({ path: f, exists: path.resolve(f).startsWith("/") && fs.existsSync(path.resolve(f)) })));'],
  ['console.warn(`[BatchVideoPrompt] Shot ${shot.sequence} image-based request failed, trying text-only:`, imageErr?.message?.substring(0, 200));', 'logger.warn(`Shot ${shot.sequence} image-based request failed, trying text-only`, imageErr?.message?.substring(0, 200));'],
  ['console.log(`[BatchVideoPrompt] Shot ${shot.sequence} text-only request succeeded`);', 'logger.info(`Shot ${shot.sequence} text-only request succeeded`);'],
  ['console.error(`[BatchVideoPrompt] Shot ${shot.sequence} text-only request also failed:`, textErr?.message?.substring(0, 200));', 'logger.error(`Shot ${shot.sequence} text-only request also failed`, textErr?.message?.substring(0, 200));'],
  ['console.log(`[BatchVideoPrompt] Shot ${shot.sequence} using fallback prompt`);', 'logger.info(`Shot ${shot.sequence} using fallback prompt`);'],
  ['console.log(`[BatchVideoPrompt] Shot ${shot.sequence} done (${((Date.now() - shotStart) / 1000).toFixed(1)}s, ${index + 1}/${eligible.length})`);', 'logger.info(`Shot ${shot.sequence} done (${((Date.now() - shotStart) / 1000).toFixed(1)}s, ${index + 1}/${eligible.length})`);'],
  ['console.error(`[BatchVideoPrompt] Shot ${shot.sequence} failed (${index + 1}/${eligible.length}):`, err);', 'logger.error(`Shot ${shot.sequence} failed (${index + 1}/${eligible.length})`, err);'],
  ['console.log(`[BatchVideoPrompt] Done: ${okCount} ok, ${errCount} errors, total ${((Date.now() - bvpStartTime) / 1000).toFixed(1)}s`);', 'logger.info(`Done: ${okCount} ok, ${errCount} errors, total ${((Date.now() - bvpStartTime) / 1000).toFixed(1)}s`);'],
  ['console.log(`[BatchRefImage] Shot ${shot.sequence}: generated ref image "${entry.id}"`);', 'logger.debug(`Shot ${shot.sequence}: generated ref image "${entry.id}"`);'],
  ['console.warn(`[BatchRefImage] Shot ${shot.sequence}: failed ref image "${entry.id}":`, err);', 'logger.warn(`Shot ${shot.sequence}: failed ref image "${entry.id}"`, err);'],
  ['console.log(`[SingleRefImage] Shot ${shot.sequence}: generating scene-only ref image "${refImageId}"`);', 'logger.debug(`Shot ${shot.sequence}: generating scene-only ref image "${refImageId}"`);'],
  ['console.warn(`[GenerateRefPrompts] strict filter empty (versionId=${batchVersionId}), falling back to no-version filter`);', 'logger.warn(`strict filter empty (versionId=${batchVersionId}), falling back to no-version filter`);'],
  ['console.log(`[GenerateRefPrompts] Starting sequential batched generation: ${batches.length} batch(es) of up to ${BATCH_SIZE} shots, total ${total}`);', 'logger.info(`Starting sequential batched generation: ${batches.length} batch(es) of up to ${BATCH_SIZE} shots, total ${total}`);'],
  ['console.warn(`[GenerateRefPrompts] batch ${bi + 1}: shot ${shot.sequence} missing from LLM output`);', 'logger.warn(`batch ${bi + 1}: shot ${shot.sequence} missing from LLM output`);'],
  ['console.warn(`[GenerateRefPrompts] Shot ${shot.sequence}: AI did not emit \'characters\' field`);', 'logger.warn(`Shot ${shot.sequence}: AI did not emit \'characters\' field`);'],
  ['console.log(`[GenerateRefPrompts] ✓ batch ${bi + 1}/${batches.length} (${batch[0].sequence}..${batch[batch.length - 1].sequence}): ${batchUpdated}/${batch.length} shots in ${elapsed}s`);', 'logger.info(`✓ batch ${bi + 1}/${batches.length} (${batch[0].sequence}..${batch[batch.length - 1].sequence}): ${batchUpdated}/${batch.length} shots in ${elapsed}s`);'],
  ['console.warn(`[GenerateRefPrompts] ✗ batch ${bi + 1}/${batches.length} failed in ${elapsed}s: ${String(err)}`);', 'logger.warn(`✗ batch ${bi + 1}/${batches.length} failed in ${elapsed}s`, String(err));'],
];

let replacedCount = 0;
replacements.forEach(([oldStr, newStr]) => {
  if (content.includes(oldStr)) {
    content = content.replace(oldStr, newStr);
    replacedCount++;
  }
});

console.log(`Replaced ${replacedCount} patterns in ${filePath}`);
fs.writeFileSync(filePath, content, 'utf-8');